name: Bookdown

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🏗 Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Install bookdown
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'bookdown'))"
          Rscript -e "install.packages('reticulate')"
          Rscript -e "install.packages('tinytex')"
          Rscript -e "tinytex::install_tinytex()"

      - name: Build book
        run: make

      - name: Upload book
        uses: actions/upload-artifact@v2
        with:
          name: Bookdown
          path: Bookdown

  deploy:
    name: 📦 Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download HTML
        uses: actions/download-artifact@v2
        with:
          name: Bookdown
          path: Bookdown

      - name: Upload book to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Bookdown
